language: python

python:
  - "2.6"
  - "2.7"

before_install:
  - sudo apt-get update
  - sudo apt-get install redis-server
  - sudo apt-get install libevent-dev liblzma-dev libssl-dev
  - sudo apt-get install swig

install:
## This below should be separated when core lives elsewhere
# Install core tests reqs
  - pip install -rdepends/docker-registry-core/requirements/test.txt
  - pip install -rdepends/docker-registry-core/requirements/style.txt
# Install core itself
  - pip install depends/docker-registry-core/

# Install our tests requirements, and ourselves
  - pip install -rrequirements/test.txt
  - pip install .

before_script:
  - redis-server &

script:
  - SETTINGS_FLAVOR=test DOCKER_REGISTRY_CONFIG=config_sample.yml flake8
  - SETTINGS_FLAVOR=test DOCKER_REGISTRY_CONFIG=config_sample.yml python setup.py nosetests
  - cd depends/docker-registry-core && python setup.py nosetests
